
#Interception Settings
[settings]
	#Whether if intercept all the explosions
	InterceptALL = false
	#If the Exploder can be found, intercept the explosion
	InterceptExploder = false
	#If the SourceMob can be found, intercept the explosion
	InterceptSourceMob = true
	#Print the Exploder info and CanonicalName
	PrintExploder = true
	#Enable the WhiteList
	EnableWhiteList = true
	#Add the CanonicalName of Exploder's class, the added classes will not intercept
	#Example:WhiteList = ["mekanism.additions.common.entity.EntityObsidianTNT", "mekanism.additions.common.entity.baby.EntityBabyCreeper" ,"net.minecraft.entity.monster.CreeperEntity","net.minecraft.entity.item.TNTEntity"]
	WhiteList = ["", ""]

